apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mmoqn0r8i-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/mmoqn0r8i-nodejs-gitops